name: DPM+
on:
  schedule:
    - cron: '*/10 * * * *' # Toutes les 10 minutes
  workflow_dispatch: # Permet de cliquer sur "Run" manuellement

jobs:
  check-match:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Accélère les prochains runs

      - name: Install Dependencies
        run: pip install requests

      - name: Run Tracker
        env:
          RIOT_KEY: ${{ secrets.RIOT_KEY }}
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: python OPGG_.py
